name: Auto Scrape Berita Detik

on:
  push:
    branches:
      - main
  schedule:
    # Jalan otomatis setiap 1 jam
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Scraper Detik
      env:
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASS: ${{ secrets.MONGO_PASS }}
        MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
        MONGO_DB: Capstone
        MONGO_COLLECTION: Data_Detik
      run: |
        python scraper_detik.py
